services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloudservice_db