services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloudservice_db

  minio:
    image: minio/minio
    ports:
      - '9000:9000'  # S3 API endpoint
      - '9001:9001'  # Web console
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"